// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlWtfMHB9TIvsyqH9ZEJQiR4Hn5FKzGXI',
    appId: '1:1054766309339:web:abc123def456',
    messagingSenderId: '1054766309339',
    projectId: 'ridermatch-ee4fe',
    authDomain: 'ridermatch-ee4fe.firebaseapp.com',
    storageBucket: 'ridermatch-ee4fe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlWtfMHB9TIvsyqH9ZEJQiR4Hn5FKzGXI',
    appId: '1:1054766309339:android:af391a2cf9793afa5811fe',
    messagingSenderId: '1054766309339',
    projectId: 'ridermatch-ee4fe',
    storageBucket: 'ridermatch-ee4fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd9TDYx1B9uQUYeUrKrTls4_Lc44liiSI',
    appId: '1:1054766309339:ios:0f44b9a14fb813a15811fe',
    messagingSenderId: '1054766309339',
    projectId: 'ridermatch-ee4fe',
    storageBucket: 'ridermatch-ee4fe.firebasestorage.app',
    iosBundleId: 'com.example.riderMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd9TDYx1B9uQUYeUrKrTls4_Lc44liiSI',
    appId: '1:1054766309339:ios:0f44b9a14fb813a15811fe',
    messagingSenderId: '1054766309339',
    projectId: 'ridermatch-ee4fe',
    storageBucket: 'ridermatch-ee4fe.firebasestorage.app',
    iosBundleId: 'com.example.riderMatch',
  );
}
