class BikeConfig {
  static const Map<String, List<String>> manufacturers = {
    'Royal Enfield': [
      'Classic 350',
      'Bullet 350',
      'Himalayan 450',
      'Interceptor 650',
      'Continental GT 650',
      'Meteor 350',
      'Shotgun 650',
      'Hunter 350',
    ],
    'Bajaj': [
      'Pulsar NS200',
      'Pulsar RS200',
      'Dominar 400',
      'Dominar 250',
      'Avenger Cruise 220',
      'Pulsar N250',
      'Pulsar F250',
    ],
    'TVS': [
      'Apache RTR 160 4V',
      'Apache RTR 200 4V',
      'Apache RR 310',
      'Ronin',
      'Raider 125',
    ],
    'KTM': [
      'Duke 200',
      'Duke 250',
      'Duke 390',
      'RC 200',
      'RC 390',
      'Adventure 390',
      'Adventure 250',
    ],
    'Honda': [
      'CB350 H\'ness',
      'CB350RS',
      'CB300R',
      'CB300F',
      'Hornet 2.0',
      'CBR 650R',
      'Africa Twin',
    ],
    'Hero': [
      'XPulse 200 4V',
      'Karizma XMR',
      'Mavrick 440',
      'Xtreme 160R 4V',
      'Xtreme 200S 4V',
    ],
    'Suzuki': [
      'Gixxer SF 250',
      'Gixxer 250',
      'V-Strom SX',
      'Hayabusa',
      'Katana',
    ],
    'Yamaha': [
      'MT-15 V2',
      'R15 V4',
      'R15M',
      'FZ-S FI V4',
      'FZ-X',
      'MT-03',
      'R3',
    ],
    'Jawa / Yezdi': [
      'Jawa 350',
      'Jawa 42',
      'Yezdi Adventure',
      'Yezdi Scrambler',
      'Yezdi Roadster',
    ],
    'Triumph': [
      'Speed 400',
      'Scrambler 400 X',
      'Trident 660',
      'Tiger Sport 660',
      'Tiger 900',
    ],
  };

  static const List<String> bloodGroups = [
    'A+',
    'A-',
    'B+',
    'B-',
    'O+',
    'O-',
    'AB+',
    'AB-',
  ];
}
